route:
  group_by: ['alertname'] # Group by alert name
  group_wait: 30s # Wait time before sending the first notification
  group_interval: 5m # Interval between notifications
  repeat_interval: 1h # Interval to resend notifications
  receiver: 'email-notifications' # Default receiver
receivers:
  - name: 'email-notifications' # Receiver name
    email_configs:
      - to: shubhammutkalwar@gmail.com # Email recipient
        from: test@gmail.com # Email sender
        smarthost: smtp.gmail.com:587 # SMTP server
        auth_username: shubhammutkalwar@gmail.com # SMTP auth username
        auth_identity: shubhammutkalwar#gmail.com # SMTP auth identity
        auth_password: "saved in doc" # SMTP auth password
        send_resolved: true # Send notifications for resolved alerts Inhibition Rules
inhibit_rules:
  - source_match:
      severity: 'critical' # Source alert severity
    target_match:
      severity: 'warning' # Target alert severity
    equal: ['alertname', 'dev', 'instance'] # Fields to match
